---
title: "Proyecto Final"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(dplyr)
library(sf)
library(DT)
library(ggplot2)
library(plotly)
library(leaflet)
library(shiny)
library(readxl)
library(lubridate)
library(stringi)
```

```{r datos-distritos}
distritos <-
  st_read(dsn = "distritos_simplificados.geojson", quiet = TRUE) %>%
  st_transform(4326)
```

```{r datos-delitos}
delitos_oij <-
  readxl::read_excel("estadisticaspoliciales2021.xls")
```

```{r datos-delitos-fecha}
delitos_oij$Fecha <-
  as.Date(delitos_oij$Fecha, format("%d/%m/%Y"))
```

```{r lista-provincias}
lista_provincias <- unique(delitos_oij$Provincia)
lista_provincias <- sort(lista_provincias)
lista_provincias <- c("Todas", lista_provincias)
```

```{r lista-cantones}
lista_cantones <- unique(delitos_oij$Canton)
lista_cantones <- sort(lista_cantones)
lista_cantones <- c("Todos", lista_cantones)
```

```{r lista-distritos}
lista_distritos <- unique(delitos_oij$Distrito)
lista_distritos <- sort(lista_distritos)
lista_distritos <- c("Todos", lista_distritos)
```

```{r lista-delitos}
lista_delitos <- unique(delitos_oij$Delito)
lista_delitos <- sort(lista_delitos)
lista_delitos <- c("Todos", lista_delitos)
```

```{r lista-victima}
lista_victima <- unique(delitos_oij$Victima)
lista_victima <- sort(lista_victima)
lista_victima <- c("Todas", lista_victima)
```

```{r lista-genero}
lista_genero <- unique(delitos_oij$Genero)
lista_genero <- sort(lista_genero)
lista_genero <- c("Todos", lista_genero)
```

```{r lista-edad}
lista_edad <- unique(delitos_oij$Edad)
lista_edad <- sort(lista_edad)
lista_edad <- c("Todas", lista_edad)
```

column {.sidebar}
-----------------------------

### **Fuente de los datos: [Organismo de Investigación Judicial (OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)**

```{r filtros}
h3("Filtro de datos")
selectInput(
  inputId = "Provincia",
  label = "Provincia",
  choices = lista_provincias,
  selected = "Todas"
)
selectInput(
  inputId = "Canton",
  label = "Cantón",
  choices = lista_cantones,
  selected = "Todos"
)
selectInput(
  inputId = "Distrito",
  label = "Distrito",
  choices = lista_distritos,
  selected = "Todos"
)
selectInput(
  inputId = "Delito",
  label = "Delito",
  choices = lista_delitos,
  selected = "Todos"
)
selectInput(
  inputId = "Victima",
  label = "Víctima",
  choices = lista_victima,
  selected = "Todas"
)
selectInput(
  inputId = "Genero",
  label = "Género",
  choices = lista_genero,
  selected = "Todos"
)
selectInput(
  inputId = "Edad",
  label = "Edad",
  choices = lista_edad,
  selected = "Todas"
)
```

```{r}
filtrarDelitos <- reactive({
  delitos_filtrados <- delitos_oij
  
  if (input$Provincia != "Todas"){
    delitos_filtrados <-
      delitos_filtrados %>%
      filter(Provincia == input$Provincia)
    
    if (input$Canton == "Todos") {
      distritos_provincia <- filter(delitos_oij, Provincia == input$Provincia)
      lista_cantones <- unique(distritos_provincia$Canton)
      lista_cantones <- sort(lista_cantones)
      lista_cantones <- c("Todos", lista_cantones)
      
      updateSelectInput(
        session,
        "Canton",
        label = "Cantón",
        choices = lista_cantones,
        selected = "Todos"
      )
    }
  }
  if (input$Canton != "Todos") {
    delitos_filtrados <-
      delitos_filtrados %>%
      filter(Canton == input$Canton)
    
    if (input$Distrito == "Todos") {
      distritos_canton <- filter(delitos_oij, Canton == input$Canton)
      lista_distritos <- unique(distritos_canton$Distrito)
      lista_distritos <- sort(lista_distritos)
      lista_distritos <- c("Todos", lista_distritos)
      
      updateSelectInput(
        session,
        "Distrito",
        label = "Distrito",
        choices = lista_distritos,
        selected = "Todos"
      )
    }
  }
  if (input$Distrito != "Todos") {
    delitos_filtrados <-
      delitos_filtrados %>%
      filter(Distrito == input$Distrito)
  }
  if (input$Delito != "Todos") {
    delitos_filtrados <-
      delitos_filtrados %>%
      filter(Delito == input$Delito)
  }
  if (input$Victima != "Todas") {
    delitos_filtrados <-
      delitos_filtrados %>%
      filter(Victima == input$Victima)
  }
  if (input$Genero != "Todos") {
    delitos_filtrados <-
      delitos_filtrados %>%
      filter(Genero == input$Genero)
  }
  if (input$Edad != "Todas") {
    delitos_filtrados <-
      delitos_filtrados %>%
      filter(Edad == input$Edad)
  }
  return(delitos_filtrados)
})
```

Column {data-width=550}
---------------------

### Mapa

```{r}
distritos <-
  distritos %>%
  mutate(distrito_normalizado = tolower(stri_trans_general(distrito, id = "Latin-ASCII")))
```

```{r}
delitos_oij <-
  delitos_oij %>%
  mutate(distrito_normalizado = tolower(stri_trans_general(Distrito, id = "Latin-ASCII")))
```

```{r}
delitos_oij <-
  delitos_oij %>%
  mutate(Distrito = if_else(Distrito == "CAIRO", "EL CAIRO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "FORTUNA", "LA FORTUNA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "HORQUETAS", "LAS HORQUETAS", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "GENERAL", "EL GENERAL", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "SAN JOSE DE LA MONTA?A", "SAN JOSE DE LA MONTANA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MACACOMA", "MACACONA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "SAN FRANCISCO", "AGUACALIENTE O SAN FRANCISCO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "CEIBA", "LA CEIBA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "CORTES", "PUERTO CORTES", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "LA GARITA", "GARITA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "LA AMISTAD", "LA  AMISTAD", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "SAN JOSE (PIZOTE)", "SAN JOSE O PIZOTE", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "JIMENEZ", "PUERTO JIMENEZ", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "LOS ANGELES", "ANGELES", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "GUADALUPE", "GUADALUPE O ARENILLA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "ASUNCION", "LA ASUNCION", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MASTATE", "EL MASTATE", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "UNION", "LA UNION", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MATA PLATANO", "MATA DE PLATANO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "AGUA BUENA", "AGUABUENA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "ROSARIO", "EL ROSARIO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "PALMERA", "LA PALMERA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "TIGRA", "LA TIGRA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "MERECEDES", "MERCEDES", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "FORTUNA", "LA FORTUNA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "DRAKE", "BAHIA DRAKE", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "GRANJA", "LA GRANJA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "CURE?A", "CURENA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "EL CHIRRIPO", "CHIRRIPO", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "LA LEGUA", "LEGUA", Distrito)) %>%
  mutate(Distrito = if_else(Distrito == "TAPEZCO", "TAPESCO", Distrito))
```

```{r}
delitos_oij <-
  delitos_oij %>%
  left_join(
    dplyr::select(
      st_drop_geometry(distritos),
      codigo_dta,
      cod_canton,
      distrito_normalizado
    ),
    by = c("distrito_normalizado" = "distrito_normalizado"),
    copy = FALSE,
    keep = FALSE
  )
```

```{r}
delitos_x_distrito <-
  delitos_oij %>%
  count(codigo_dta, name = "delitos")
```

```{r}
distritos_delitos <-
  distritos %>%
  left_join(
    delitos_x_distrito,
    by = "codigo_dta",
    copy = FALSE,
    keep = FALSE
  )
```

```{r}
colores_distritos_delitos <-
  colorNumeric(palette = "Reds",
               domain = distritos_delitos$delitos,
               na.color = "white")
```

```{r}
renderLeaflet({
  delitos_oij <- filtrarDelitos()
  
  leaflet() %>%
    setView(
      lng = -84.19452,
      lat = 9.572735,
      zoom = 7
    ) %>%
    addTiles(group = "OpenStreetMap") %>%
    addPolygons(
      data = distritos,
      fillColor = ~ colores_distritos_delitos(distritos_delitos$delitos),
      fillOpacity = 0.8,
      color = "black",
      weight = 1.0,
      popup = paste(
        paste("<strong>Provincia:</strong>",
              distritos_delitos$provincia),
        paste("<strong>Cantón:</strong>",
              distritos_delitos$canton),
        paste("<strong>Distrito:</strong>",
              distritos$distrito),
        paste("<strong>Cantidad de delitos:</strong>",
              distritos_delitos$delitos),
        sep = "<br/>"
      ),
      group = "Delitos en distritos"
    ) %>%
    addLayersControl(
      baseGroups = c("OpenStreetMap"),
      overlayGroups = c("Delitos en distritos")
    ) %>%
    addLegend(
      position = "bottomleft",
      pal = colores_distritos_delitos,
      values = distritos_delitos$delitos,
      group = "Delitos en distritos",
      title = "Cantidad de delitos"
    )
})
```

### Tabla

```{r}
renderDT({
  delitos_oij <- filtrarDelitos()
  
delitos_oij %>%
  dplyr::select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton, Distrito) %>%
  datatable(colnames = c("Delito", "Fecha", "Víctima", "Edad", "Género", "Provincia", "Cantón", "Distrito"),
            options = list(
              pageLenght = 5,
              language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
            ))
})
```

Column {data-width=250}
-----------------------------------------------------------------------

### Cantidad de delitos por delito

```{r grafico-delitos, message=FALSE, echo=FALSE}
renderPlotly({
  delitos_oij <- filtrarDelitos()

  grafico_delitos <-
    delitos_oij %>%
    count(Delito) %>%
    ggplot(aes(x = reorder(Delito, n), y = n)) +
    geom_bar(stat = "identity") +
    ggtitle("Cantidad de delitos por delito") +
    xlab("Delito") +
    ylab("Cantidad de delitos") +
    coord_flip() +
    theme_minimal()
  
  ggplotly(grafico_delitos) %>% config(locale = "es")
})
```

### Cantidad de delitos por víctima

```{r grafico-victimas, message=FALSE, echo=FALSE}
renderPlotly({
  delitos_oij <- filtrarDelitos()

grafico_victimas <-
  delitos_oij %>%
  count(Victima) %>%
  ggplot(aes(x = reorder(Victima, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por víctima") +
  xlab("Víctima") +
  ylab("Cantidad de delitos") +
  coord_flip() +
  theme_classic()

ggplotly(grafico_victimas) %>% config(locale = "es")
})
```

Row {data-width=300}
-------------------------------------------

### Cantidad de delitos por mes

```{r data-mes, message=FALSE, echo=FALSE}
meses_delitos <-
  delitos_oij %>%
  mutate(Meses = lubridate::month(Fecha, label = TRUE))
```

```{r grafico-mes, message=FALSE, echo=FALSE}
renderPlotly({
  delitos_oij <- filtrarDelitos()

grafico_mes <-
  meses_delitos %>%
  count(Meses) %>%
  ggplot(aes(x = Meses, y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos por mes") +
  xlab("Mes") +
  ylab("Cantidad de delitos") +
  theme_minimal()

ggplotly(grafico_mes) %>% config(locale = "es")
})
```

### Proporción de género por delito

```{r grafico-genero, message=FALSE, echo=FALSE}
renderPlotly({
  delitos_oij <- filtrarDelitos()

grafico_genero <-
  delitos_oij %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Delitos por género") +
  xlab("Delito") +
  ylab("Proporción") +
  labs(fill = "Género") +
  coord_flip() +
  theme_minimal()

ggplotly(grafico_genero) %>% config(locale = "es")
})
```

### Proporción de edad por delito

```{r grafico-edad, message=FALSE, echo=FALSE}
renderPlotly({
  delitos_oij <- filtrarDelitos()

grafico_edad <-
  delitos_oij %>%
  ggplot(aes(x = Delito, fill = Edad)) +
  geom_bar(position = "fill") +
  ggtitle("Delitos por edad") +
  xlab("Delito") +
  ylab("Proporción") +
  labs(fill = "Edad") +
  coord_flip() +
  theme_minimal()

ggplotly(grafico_edad) %>% config(locale = "es")
})
```
